@startmindmap
scale max 2048 width

* potential\nTinyML\nplatformer
**[#cyan] **Milli**\n **AI**
*** MVP
**** Operator
*****[#cyan] **Telia**
******_ smart building
*****_ other use cases coming...
**** Enterprise
*****[#cyan] **Tranxens**
******_ smart logistics
*** ongoing discussion
**** ABB
**** Husquvarna
**** Assa Abloy
**** BalticYachts
*****_ smart cabin
**** City of Helsinki
*** partner
****[#cyan] **Linux Foundation**
***** AI
******_ opensource\nincubation
**** semiconductor
***** Himax
***** Greenwaves Technologies
**** Skymizer
*****_ tool: ML compiler
**** Plumerai
*****_ BNN algorithm
**** Edge Impulse
*****_ tool: general
*** E///
****[#cyan] **IoT Accelerator**
***** DMDC
***** DCP
**** Ardesco SDK
*****_ NB-IoT reference
**** BDGS

@endmindmap


