@startuml
title ML compiler: computation graph conversion

rectangle resource {
        database model
        database data
}
file Owl.cgraph #aaaaaa
note bottom of Owl.cgraph : 456KB
file TF.cgraph #aaaaaa
note right of TF.cgraph : 1,372KB
file TFLite.cgraph #aaaaaa
note right of TFLite.cgraph : 429KB\n111KB?
file ONNX.cgraph #aaaaaa
note right of ONNX.cgraph : ???KB
folder MirageOS {
        folder custom_runtime {
        	file "custom\nmodel"
	}
}

Owl.cgraph -down-> TF.cgraph : conversion
Owl.cgraph .[dotted]> ONNX.cgraph
ONNX.cgraph .[dotted]> TF.cgraph
resource .[dotted]> (TensorFlow) : training
(TensorFlow) .[dotted]> TF.cgraph
TF.cgraph -down-> TFLite.cgraph : optimization
TFLite.cgraph -down-> (TFL micro\nruntime) : built-in
(TFL micro\nruntime) -> MirageOS : built-in

resource -down-> (OCaml\nOwl) : training
(OCaml\nOwl) -> Owl.cgraph : generated
(OCaml\nOwl) <- Owl.cgraph
(OCaml\nOwl) -> TF.cgraph : conversion
(TFLite) <- TF.cgraph
(TFLite) -> TFLite.cgraph : conversion

@enduml
