@startuml
title Inference Usecase

actor client

note "TCP/IP" as tcpip

(WiFi\nAccess\nPoint) <..> client

rectangle ESP32 {
        (WiFi\nAccess\nPoint) <..> (MirageOS/\nFreeRTOS)
        client -right- tcpip: "send\nbitmap"
        tcpip -right-> (MirageOS/\nFreeRTOS)
        (MirageOS/\nFreeRTOS) -up-> (TFLM\nruntime): "ask\nprediction"
        (TFLM\nruntime) -down-> (MirageOS/\nFreeRTOS): "return\nresult"
}
(MirageOS/\nFreeRTOS) -down-> (display): "show result"

newpage
skinparam TitleFontSize 24
skinparam legendFontSize 20
'title \nML inference on MCU

actor laptop
note "TCP/IP" as tcpip
laptop  <.up.> (WiFi\nAccess\nPoint)
laptop -right- tcpip: "send\nbitmap"

rectangle ESP32 #b8cecd {
        rectangle ML #ff7373 {
                file model
                (runtime)
                model . runtime
        }
        (Unikernel)
        (WiFi\nAccess\nPoint) <.down.> (Unikernel)
        (Unikernel) -up-> (runtime): "ask\nprediction"
        (runtime) -down-> (Unikernel): "return\nresult"
}

legend
MCU: ESP32
ARCH: Xtensa 32bit
RAM: 520KB SRAM
ROM: 4MB FLASH
160MHz / 600 DMIPS
end legend

tcpip -right-> (Unikernel)
(Unikernel) -down-> (display): "show result"

@enduml
