@startmindmap
scale 1.2
'title PoC outline
+ PoC
++ Training
+++_ Federated Learning (FL)
+++_ OCaml Owl
+++_ MirageOS
+++_ KVM (x86)
++ Compile
+++_ cgraph
++++_ Owl
++++_ TensorFlow (TF)
++++_ TF Lite (TFL)
++++_ TFL for micro (TFLM)
+++_ TFLM runtime
++ Inference
+++_ TFLM runtime
+++_ MirageOS
+++_ FreeRTOS
+++_ ESP32 (Xtensa)
@endmindmap
