@startmindmap
scale 1.2
title PoC outline
+ PoC
++ training
+++_ Federated Learning (FL)
+++_ OCaml Owl
+++_ MirageOS
++ compile
+++_ cgraph
++++_ Owl
++++_ TensorFlow (TF)
++++_ TF Lite (TFL)
++++_ TFL for micro (TFLM)
+++_ TFLM runtime
++ inference
+++_ ESP32 devkit
+++_ MirageOS
+++_ TFLM runtime
@endmindmap
