@startuml
title Inference Sequence

actor laptop

box "ESP32"
participant MirageOS
participant TFLM
participant display
end box

laptop -> MirageOS: send bitmap
MirageOS -> TFLM: ask prediction
activate TFLM
TFLM -> TFLM: run inference
MirageOS <-- TFLM: return result
deactivate TFLM
MirageOS -> display: show result

MirageOS --> laptop: result

@enduml

