@startuml
title PoC sequence
|TF Lite\nlaptop|
start
|#AntiqueWhite|OCaml Owl\nMirageOS\nKVM|
:train a model;
:generate cgraph;
:convert cgraph;
|TF Lite\nlaptop|
:compile cgraph;
:build runtime\nwith cgraph;
:build unikernel\nwith runtime;
|MirageOS\nFreeRTOS\nESP32 Xtensa|
:run inference;
:show result;
stop
@enduml
