@startgantt
scale 3

printscale weekly
saturday are closed
sunday are closed
Project starts the 1st of january 2021

-- Common --
[summer vacation] starts at 2021/7/1
[summer vacation] ends at 2021/7/31
[SaaS implementation on Cloud] starts at 2021/2/1
[SaaS implementation on Cloud] lasts 90 days
[Pioneer's Nest] happens at 2021/9/16
[Traxens start] happens at 2021/4/1
[Traxens end] happens at 2021/6/31
[Implementation done] happens at 2021/6/31


-- Traxens --
[porting TinyML on device] starts at 2021/4/1
[porting TinyML on device] lasts 30 days
[data acqusition] starts at 2021/4/1
[data acqusition] ends at 2021/4/31
[ML model squeeze] starts at [data acqusition]'s end
[ML model squeeze] lasts 20 days

[Traxens evaluation] starts at [ML model squeeze]'s end
[Traxens evaluation] ends at 2021/6/31

-- Telia --
[Telia specification] starts at 2020/12/1
[Telia specification] ends at 2021/1/15
[camera selection] starts at [Telia specification]'s end
[camera selection] ends at 2021/1/31
[porting TinyML on camera] starts at [camera selection]'s end
[porting TinyML on camera] ends at 2021/3/30
[training data collection] starts at [porting TinyML on camera]'s end
[training data collection] lasts 10 days
[human detection training] starts at [training data collection]'s end
[human detection training] lasts 30 days
[human detection squeezing] starts at [human detection training]'s end
[human detection squeezing] ends at 2021/6/30
[Telia evaluation] starts at 2021/8/1
[Telia evaluation] ends at 2021/9/15

@endgantt
