@startgantt

title MVP execution plan

scale 5
printscale weekly
saturday are closed
sunday are closed
Project starts the 1st of january 2021

-- common task --
[implement SaaS on Azure] starts at 2021/2/1
[implement SaaS on Azure] ends at 2021/5/1

-- **(T)** Telia, smart building, occupancy management --
[**(T)** specify requirements] starts at 2021/1/15 and ends at 2021/3/1
[**(T)** select IoT sensor] starts at 2021/3/1 and lasts 7 days
[**(T)** port TinyML on IoT sensor] starts at [**(T)** select IoT sensor]'s end and lasts 30 days
[**(T)** acquire IoT sensor data] starts at 2021/4/1 and lasts 30 days
[**(T)** train ML model] starts at [**(T)** acquire IoT sensor data]'s end and lasts 14 days
[**(T)** squeeze ML model] starts at 2021/6/1 and lasts 30 days
[**(T)** field testing] starts at [**(T)** squeeze ML model]'s end and lasts 30 days

-- **(X)** Traxens, smart logistics, monitoring shipping containers--
[**(X)** port TinyML on IoT sensor] starts at 2021/2/15 and lasts 30 days
[**(X)** acquire IoT sensor data] starts at 2021/4/1 and lasts 7 days
[**(X)** train ML model] starts at 2021/4/20 and lasts 14 days
[**(X)** squeeze ML model] starts at 2021/5/1 and lasts 14 days
[**(X)** field testing] starts at [**(X)** squeeze ML model]'s end and lasts 30 days

-- **(B)** BalticYachts, smart cabing, human flow control --
[**(B)** specify requirements] starts at 2020/12/15 and ends at 2021/1/15
[**(B)** select IoT sensor] starts at [**(B)** specify requirements]'s end and lasts 7 days
[**(B)** port TinyML on IoT sensor] starts at [**(B)** select IoT sensor]'s end and lasts 30 days
[**(B)** acquire IoT sensor data] starts at 2021/3/1 and lasts 30 days
[**(B)** train ML model] starts at [**(B)** acquire IoT sensor data]'s end and lasts 14 days
[**(B)** squeeze ML model] starts at [**(B)** train ML model]'s end and lasts 14 days
[**(B)** field testing] starts at [**(B)** squeeze ML model]'s end and lasts 14 days

-- evaluation --
[evaluate\ncommercial\ndeployment] starts at 2021/8/1 and lasts 30 days

@endgantt
