@startuml

'title TinyMLaaS in MXE

actor vendor

cloud Cloud {
        collections "ML\nframeworks" as mlf
        database model\nzoo {
                collections models
        }
        database "container\nrepository" as container_repository
        mlf -left-> models : register

       Rectangle MXE #lightgreen {
		database build {
                	rectangle TinyMLaaS #yellow {
                	        collections ML_compiler1 <<vendor>> #Aqua

				vendor -[#blue,dotted]down-> ML_compiler1
                	}
		}
                rectangle Orchestrator {
                        collections image1
                }
                TinyMLaaS -[#blue,bold]> container_repository : register
	        build <-up- models : download
        }

}

'note top of MXE
'MXE:
'- Build server
'- Orchestrator
'- Container registory?
'end note

cloud Edge {
        container_repository -down-> image1 : pull

        rectangle edge1 {
                rectangle host1 {
                        (Container\nRuntime) as containerd
                        rectangle inference1 {
                                file model1
                                file runtime1
                                runtime1 .right. model1
                        }
                }
                usecase HW1 as "CPU1
                        ..
                        RAM1
                        ..
                        ROM1
                        ..
                        **HWA1**"
        }

        containerd -[#blue,bold]up-> ML_compiler1 : **info**
        image1 -down-> containerd : pull
        containerd -> inference1 : run
}

collections devices

devices -up-> inference1 : ask\ninference
devices <-up-- inference1 : return\nresult


legend left
|= |= who does? |
|<back:lightgreen>        </back>|    MXE    |
|<back:yellow>        </back>|    TinMLaaS framework    |
|<back:aqua>        </back>|    HW vendor provides    |
end legend

@enduml
