@startuml
newpage
title Edge base IoT
actor maintainer
cloud "Edge\n" #lightgray {
        (ML\nprediction) #yellow
}
rectangle "machine\n" #cyan {
        (gateway)
        (sensor\n1) #lightgreen
        (sensor\n2) #lightgreen
        (failing\ncomponent)
}
(sensor\n1) -[bold]up-> (gateway) : raw\ndata\n1
(sensor\n2) -[bold]up-> (gateway) : raw\ndata\n2
(gateway) --[bold]up-> (ML\nprediction) : raw\ndata\n1
(gateway) --[bold]up-> (ML\nprediction) : raw\ndata\n2
maintainer -[#blue,bold]down-> (failing\ncomponent) : replace\nbefore\nfailure
(ML\nprediction) .[dotted]left.> maintainer : notification
newpage
title TinyML with NB-IoT
actor maintainer
cloud "Edge\n" #lightgray {
        (forward)
}
rectangle "machine\n" #cyan {
        (ML\nprediction) #yellow
        (sensor\n1) #lightgreen
        (sensor\n2) #lightgreen
        (failing\ncomponent)
}
(sensor\n1) -[bold]up-> (ML\nprediction) : raw\ndata\n1
(sensor\n2) -[bold]up-> (ML\nprediction) : raw\ndata\n2
(ML\nprediction) --[dotted]up-> (forward) : notification\nNB-IoT
maintainer -[#blue,bold]right-> (failing\ncomponent) : replace\nbefore\nfailure
(forward).[dotted]left.> maintainer : notification
@enduml
