@startuml

cloud Compiler

folder image2 {
        file model2 <<OPs2>>
        (runtime2) <<OPs2>>
	model2 #=# runtime2 : pair
}

rectangle device {
        folder HWA1 {
		folder image1 {
	                file model1 <<OPs1>>
	                (runtime1) <<OPs1>>
                }
	}
	model1 #=# runtime1 : pair
	(runtime1) #-[dotted]# HWA1
}

Compiler <-down- (runtime2) : update
Compiler -down-> (runtime1) : replace
HWA1 .> Compiler : info

newpage

cloud Orchestrator

rectangle device1 {
	folder image1 {
	        file model1 <<OPs1>>
	        (runtime1) <<OPs1>>
	}
        folder HWA1 {
		(custom ISA)
	}
        folder HWA2 {
		(FPGA)
	}
	model1 #=# runtime1 : pair
	(runtime1) #=down=# HWA1
	(runtime1) #=down=# HWA2
}

rectangle device2 {
	folder image2 {
        	file model2 <<OPs2>>
        	(runtime2) <<OPs2>>
		model2 #=# runtime2 : pair
	}
        folder HWA3
        folder HWA4
        folder HWA5
	(runtime2) #=down=# HWA3
	(runtime2) #=down=# HWA4
	(runtime2) #=down=# HWA5
}

device1 .up.> Orchestrator : info
device2 .up.> Orchestrator : info

Orchestrator =[#blue]> (runtime1) : **(1)request**
device1 =[#blue]> device2 : **(2)pass**
Orchestrator <=[#blue] device2 : **(3)return**

@enduml
