@startuml

cloud Compiler

folder image2 {
        file model2 <<OPs2>>
        (runtime2) <<OPs2>>
	model2 . runtime2 : pair
}

rectangle device {
        folder HWA {
		folder image1 {
	                file model1 <<OPs1>>
	                (runtime1) <<OPs1>>
                }
	}
	model1 . runtime1 : pair
}

Compiler <-down- (runtime2) : update
Compiler -down-> (runtime1) : replace
HWA .> Compiler : info

@enduml
