@startmindmap
scale max 2048 width

+ \n**TinyMLaaS**\n- Component1 (C1)\n- Component2 (C2)\n- Component3 (C3)\n
-- MilliAI\n- C1\n- C3
--- Ericsson ONE
---- Hanieh Chaichi
---- Jonas Almeling
-----_ **Telia**
-----_ Electrolux?
-----_ Skanska?
--- **Hiroshi Doyu**
----_ **Traxens**
----_ **ABB**
---- Sebastian Elmgren
-----_ Atlas Copco
---- Patrik Wikberg\nStrategic Product
-----_ **Baltic Yachts**
-----_ **Erillisvekot**
-----_ Nautors Swan?
---- development\npartner
-----_ Skymizer
-----_ OctoML
-----_ Plumerai
-----_ InfXL
-----_ LFAI
-----_ D15 IoT lab\nprivate LTE
++ IoTA\n- C2
+++ Ardesco\nIoT sensor
++++ Joakim Uddenfeldt\nOwner of Ardesco
+++++_ San Jose
++++ Sigma\nHardware
+++++_ Sweden
+++ **John Fornehed**\nBTEB IoT
++++ Stream Analyze
+++ BLAB\nIoT Business Lab
++++ Michael Lee\nDMDC
+++++_ Hong Kong
+++++_ Aachen
+++ Riju Rillai\nSolution / Japan
++++_ Softbank
+++++_ <s>IoT</s>
+++++_ Device?
++++_ NTT Docomo?
++++_ KDDI?

@endmindmap


