@startmindmap
skinparam TitleFontSize 32
title Standardizing 3 interfaces for ecosystem
* TinyMLaaS
** compiler plugin\ninterface
*** input
**** device info
***** HWAs
**** ML model
**** quantization
*** output
**** compiled\nmodule
***** model
***** runtime
** orchestration\nprotocol
*** LwM2M
**** SOTA
**** FOTA
** inference\nmodule format
*** 3 profiles
**** ONNX
***** ONNX runtime
**** embedded
***** SOTA
**** baremetal
***** FOTA
@endmindmap

@startmindmap
scale 1.8
title Standardizing 3 interfaces for ecosystem
* TinyMLaaS
** compiler plugin **interface**
** orchestration **protocol**
** inference module **format**
@endmindmap
