@startmindmap
skinparam TitleFontSize 32
scale 2048 width
'title Standardizing 3 interfaces for ecosystem
* TinyMLaaS
** compiler plugin\ninterface
*** input
**** device info
***** RAM
***** ROM
***** HWAs
**** ML model
**** quantization
*** output
**** compiled\nmodule
***** model
***** runtime
** orchestration\nprotocol
*** LwM2M
**** SOTA
***** live updating
**** FOTA
***** rebooting
*** Custom
**** OTA
** inference\nmodule format
*** 3 profiles
**** ONNX
***** ONNX runtime
**** embedded
***** SOTA
**** baremetal
***** FOTA
@endmindmap

@startmindmap
scale 1.8
title Standardizing 3 interfaces for ecosystem
* TinyMLaaS
** compiler plugin **interface**
** orchestration **protocol**
** inference module **format**
@endmindmap



@startmindmap
scale 1.8
* compiler plugin\n**interface**
** input
*** device info
**** RAM
**** ROM
**** HWAs
*** ML model
*** quantization
** output
*** compiled\nmodule
**** model
**** runtime
@endmindmap
@startmindmap
scale 1.8
* orchestration\n**protocol**
** LwM2M
*** SOTA
**** live updating
*** FOTA
**** rebooting
** Custom
*** OTA
@endmindmap
@startmindmap
scale 1.8
* inference\n**module format**
** 3 profiles
*** ONNX
**** ONNX runtime
*** embedded
**** SOTA
*** baremetal
**** FOTA
@endmindmap
