@startuml
newpage
scale 1.5
title (1/3) compiler plugin interface
cloud Cloud #gray {
        database Zoo #ffffff {
                collections model
        }
}
cloud TinyMLaaS #yellow {
        database Build #ffffff
        model -down-> Build : download
}
rectangle ML_compiler #lightgreen {
        collections compilers
}
Build <-[#blue,bold]right- compilers : " plugin"

newpage
scale 1.5
title (2/3) orchestration protocol via LwM2M
cloud TinyMLaaS #yellow {
        (LwM2M\nserver) as server
        database Build #ffffff {
                file "inference\nmodule" as inference_module
        }
        (server) <.right. inference_module
}
node device #skyblue {
        (LwM2M\nclient) as client
}
client .[#blue,bold,dashed]up.> server : device\ninfo
client <-[#blue,bold]- server :  SOTA\nFOTA

newpage
scale 1.5
title (3/3) inference module format
file "inference\nmodule" as inference_module
node device #skyblue {
        (LwM2M\nclient) as client
        rectangle OS #ffffff {
                (inference)
        }
}
inference_module -down-> client : LwM2M SOTA
client -[#blue,bold]> inference : update

@enduml
