@startmindmap
scale 1.5
* Problem
** issues
***_ Privacy
***_ Bandwith
***_ Latency
***_ Reliability
** gap between web & embedded
***_ diversity of embedded
** heavy ML
***_ runtime
***_ model

@endmindmap
