@startmindmap
scale 1.2
* Unikernel
** Based on Library OS
** Simple && Concise
** Configurable backend
***_ Unix
***_ Xen
***_ KVM
***_ RTOS
***_ JS/browser
** 2 types
***_ posix compatible
***_ language specific
@endmindmap
