@startmindmap
scale 2.0
* Proposal
** TinyML as-a-Service
*** Squash a ML model
*** Tailor made runtime
****_ per model
****_ per HW(A)
*** Build nano service images
****_ per HW(A)
*** Orchestration
@endmindmap
