@startmindmap
scale 1.5
* Problem
** issues
***_ Privacy
***_ Bandwith
***_ Latency
***_ Reliability
** gap: web vs embedded
***_ diversity of\nembedded
** heavy ML
***_ runtime
***_ model

@endmindmap
