@startmindmap
* ML compiler
** Input: cgraph of ML model
***_ <s>protobuf</s> => flatbuf
** Squash a model
***_ quantization
***_ fuse ops
** Tailor made runtime
***_ per ops used
***_ per HW(A)
@endmindmap
