@startmindmap
* TinyML as-a-Service\n(TinMLaaS)
** Collect device info
***_ RTOS
***_ CPU / RAM / ROM
** Find ML model
***_ model Zoo
***_ distributed training
** Squash ML model
***_ prune / fuse ops
***_ quantization
** Tailor made runtime
***_ per model
***_ per HW(A)
** Build image
***_ runtime
***_ model
** Deploy image
***_ on demand
***_ device orchestration
@endmindmap
