@startmindmap
* Edge\nProblems
** 5 issues
***_ Privacy
***_ Bandwith
***_ Latency
***_ Reliability
***_ Energy
** Web vs Embedded
***_ diversity of\nembedded
** Heavy ML
***_ runtime
***_ model

@endmindmap
