@startmindmap

* TinyML\naaS
** Unikernel
***_ Thin wrapper of RTOS
***_ Unified interface of service
** ML compiler
***_ Small model
***_ Small runtime
***_ HWA optimization
** CoAP
***_ Orchestration

@endmindmap
