@startmindmap
* TinyML as-a-Service\n(TinMLaaS)
** Find a ML model
***_ model Zoo
***_ distributed training
** Squash a ML model
***_ fuse ops
***_ quantization
** Tailor made runtime
***_ per model
***_ per HW(A)
** Build a service image
***_ runtime
***_ model
** Deploy a service image
***_ on demand
***_ device orchestration
@endmindmap
