@startmindmap

* TinyML\naaS
** Unikernel
***_ <s>posix</s>\n<s>compatible</s>
***_ language\nspecific
** ML compiler
***_ flatbuf
***_ quantization
***_ fuse
***_ HWA
** CoAP
***_ FOTA update
***_ orchestration
***_ monitoring

@endmindmap
