@startmindmap

* TinyML\naaS
** Unikernel
***_ <s>posix</s>\n<s>compatible</s>
***_ language\nspecific
** ML compiler
***_ flatbuf
***_ quantization
***_ prune / fuse
***_ HWA
** LwM2M
***_ FOTA update
***_ orchestration
***_ monitoring

@endmindmap
