@startmindmap
+ Unikernel
-- Posix\ncompatible
---_ OSv
---_ Rumprun
---_ includeOS
---_ Graphene
---_ ClickOS
---_ Nanos
++ Language\nspecific
+++_ MirageOS\n(OCaml)
+++_ HaLVM\n(Haskell)
+++_ LING\n(Erlang)
+++_ Runtime.js\n(JS)

@endmindmap
